#--        MEILER         --#
#--   build script for    --#
#--     MEI test set      --#
#--        v0.1.1         --#
#--                       --#
#--     programmed by     --#
#--   Klaus Rettinghaus   --#
#--                       --#
rm build.log
rm README.md
echo "building MEI test set"
echo "# MEI test set" >> README.md
echo "This is an autogenerated overview of the testfiles." >> README.md
find MEI-test-set/MEI -type f -name "*.mei"|while read file;
do
  fname=$(basename "$file")
  dname=$(dirname "$file")
  echo $fname
  saxonb-xslt -s:$file -xsl:mei2ly.xsl -o:${file%.mei}.ly && lilypond -dno-print-pages -dpreview --formats=png --loglevel=BASIC_PROGRESS --output=$dname ${file%.mei}.ly >> build.log 2>&1
  rm ${file%.mei}.ly

  #-- add output to README.md
  echo "### [$fname]($fname)" >> README.md
  echo "![MEILER](${file%.mei}.preview.png)" >> README.md
  echo "![Sibelius](${dname//MEI\//sibs\/}/${fname%.mei}.png)" >> README.md
done
rm -rf MEI-test-set/MEI/*/*.midi
echo see build.log for details
